### ISSUE TITLE
sandSilica oredict error

### ISSUE THREAD

**Issue by Mrthomas20121** [TFC-Metallum/TFCTech#47]
for a recipe im adding to a techreborn machine with ct, im using the oredict sandSilica added by tfctech but im getting a error because the oredict is empty.
can this be fixed in tfctech? 

https://gist.github.com/Mrthomas20121/00d979e5b6039e85d50733fd1a033716#file-crafttweaker-log-L396 crafttweaker log in case you need it.

**Comment by DisasterMoo** [comment]
Hard, but i will see what i can do. 

The problem here is that i'm using `init` phase instead of `preInit` to register that ore dict entry, mainly because that is the first safest place I can grab any TFC block/item (since the registration phase is done at the end of `preInit`). Also, it's not a CT issue, but a TechReborn one, since it does two things: 
- CT Recipe registration yet in the `preInit` phase after item registration probably (TFC for example does that at `postInit` iirc).
- Check for valid ore dict entries at recipe registration (if it didn't care you would be safe).
