### ISSUE TITLE
missing textures and model variants of certain hevea components

### ISSUE THREAD

**Issue by velocityraptor-real** [TFC-Metallum/TFCTech#77]
-missing textures and model variants for tfc components like the hevea pressure plate
-missing textures and model variants for wood blocks for other mods like tfcstorage
[picked_error.txt](https://github.com/TFC-Metallum/TFCTech/files/5587999/picked_error.txt)

**Comment by DisasterMoo** [comment]
So, there's a thing about some other addons interaction, unfortunately the system TFC adopts in 1.12 create those missing variants since one addon register a new wood type (in our case Hevea) while another one register a new block type (in TFC Storage case, food shelf). Don't take me wrongly, I will add the missing things for this specific interaction with TFC Storage, just wanted to point out this since this isn't the first and probably not the last time.
